baseURL: https://elia.doumerc.me
DefaultContentLanguage: es
title: My New Hugo Site

enableMissingTranslationPlaceholders: True

markup:
  highlight:
    style: emacs

  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: false


  goldmark:
    renderer:
      unsafe: true

taxonomies:
  composer: composers

languages:
  es:
    languageCode: es
    languageName: Español
    weight: 1

    menu:
      main:
      - name: Sobre mí
        pageRef: /bio
        weight: 1
      - name: Música
        pageRef: /composers
        weight: 2
      - name: Juegos
        pageRef: /games/leds
        weight: 3
      - name: Informática
        pageRef: /cs
        weight: 4
      
      footer:
      - name: sobre este sitio
        url: /cs/sobre_este_sitio/
        weight: 1
      - name: Registro de cambios
        url: /en/changelog/
        weight: 2
      - name: Política de privacidad
        url: /privacidad/
        weight: 3
      - name: Aviso legal
        url: /legal/
        weight: 4


      games:
      - name: LEDs
        url: /games/leds/
        weight: 1
      - name: GTA VI
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
        weight: 2

  
  en:
    languageCode: en
    languageName: English
    weight: 2

    menu:
      main:
      - name: About me
        pageRef: /bio
        weight: 1
      - name: Music
        pageRef: /composers
        weight: 2
      - name: Games
        pageRef: /games/leds
        weight: 3
      - name: Informatics
        pageRef: /cs
        weight: 4
      
      footer:
      - name: About this site
        url: /en/cs/about_this_site/
        weight: 1
      - name: Changelog
        url: /en/changelog/
        weight: 2
      - name: Privacy policy
        url: /privacidad/
        weight: 3
      - name: Legal
        url: /legal/
        weight: 4

      games:
      - name: LEDs
        url: /games/leds/
        weight: 1
      - name: GTA VI
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
        weight: 2
  
  de:
    languageCode: de
    languageName: Deutsch
    weight: 3

    menu:
      main:
      - name: Über mich
        pageRef: /bio
        weight: 1
      - name: Musik
        pageRef: /composers
        weight: 2
      - name: Spiele
        pageRef: /games/leds
        weight: 3
      - name: Informatik
        pageRef: /cs
        weight: 4
        
      footer:
      - name: Über diese Seite
        url: /de/cs/ueber_diese_seite/
        weight: 1
      - name: Änderungsprotokoll
        url: /en/changelog/
        weight: 2
      - name: Datenschutz
        url: /privacidad/
        weight: 3
      - name: Rechtlicher Hinweis
        url: /legal/
        weight: 4

      games:
      - name: LEDs
        url: /games/leds/
        weight: 1
      - name: GTA VI
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
        weight: 2
