baseURL: http://elia.doumerc.me
DefaultContentLanguage: es
title: My New Hugo Site

enableMissingTranslationPlaceholders: True

markup:
  highlight:
    style: emacs

  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: false


  goldmark:
    renderer:
      unsafe: true


languages:
  es:
    languageCode: es
    languageName: Español
    weight: 1

    menu:
      main:
      - name: Sobre mí
        url: /sobre_mi/
        weight: 1
      - name: Música
        url: /musica/
        weight: 2
      - name: Juegos
        url: /games/leds/
        weight: 3
      - name: Informática
        url: /cs/
        weight: 4
      
      footer:
      - name: sobre este sitio
        url: /cs/sobre_este_sitio/
        weight: 1
      - name: Política de privacidad
        url: /privacidad/
        weight: 2
      - name: Aviso legal
        url: /legal/
        weight: 3


      games:
      - name: LEDs
        url: /games/leds/
        weight: 1
      - name: GTA VI
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
        weight: 2

  
  en:
    languageCode: en
    languageName: English
    weight: 2

    menu:
      main:
      - name: About me
        url: /about_me/
        weight: 1
      - name: Music
        url: /music/
        weight: 2
      - name: Games
        url: /games/leds/
        weight: 3
      - name: Informatics
        url: /cs/
        weight: 4
      
      footer:
      - name: About this site
        url: /en/cs/about_this_site/
        weight: 1
      - name: Privacy policy
        url: /privacidad/
        weight: 2
      - name: Legal
        url: /legal/
        weight: 3
      - name: Log in
        url: /en/log_in
        weight: 4

      games:
      - name: LEDs
        url: /games/leds/
        weight: 1
      - name: GTA VI
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
        weight: 2
  
  de:
    languageCode: de
    languageName: Deutsch
    weight: 3

    menu:
      main:
      - name: Über mich
        url: /ueber_mich/
        weight: 1
      - name: Musik
        url: /musik/
        weight: 2
      - name: Spiele
        url: /games/leds/
        weight: 3
      - name: Informatik
        url: /cs/
        weight: 4
        
      footer:
      - name: Über diese Seite
        url: /de/cs/ueber_diese_seite/
        weight: 1
      - name: Datenschutz
        url: /privacidad/
        weight: 2
      - name: Rechtlicher Hinweis
        url: /legal/
        weight: 3
      - name: Einloggen
        url: /de/einloggen
        weight: 4

      games:
      - name: LEDs
        url: /games/leds/
        weight: 1
      - name: GTA VI
        url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
        weight: 2
